scala-js/scala-js-dom

src/main/scala/org/scalajs/dom/Idb.scala

Hi, from what I observed this is the correct typing for `IDBDatabase#version`. 
I haven't tested whether firefox still returns empty string when database is first created. It is not recommended though because within version upgrade callback one should be calling only `IDBVersionChangeEvent#newVersion` and `IDBVersionChangeEvent#oldVersion`.
Anyway webkits always return Integer, imho they have a fallback to `IDBVersionChangeEvent#newVersion` whereas firefox has/had fallback to empty string.
Either way `String` type doesn't make sense and I think that using `js.Any` just because Firefox might fall back to empty string is wrong. User of the API will know from scaladoc that he should use  `IDBVersionChangeEvent#newVersion` instead in that case.

IDBDatabase#version should be typed as Integer

---

src/main/scala/org/scalajs/dom/lib.scala

Currently it is not possible to use an event listener that takes a subclass of Event as a parameter.
This change enables any subclass of Event to be taken as a parameter of the listener.

EventTarrget.addEventListener event subclass

---

example/src/main/scala/example/Example.scala
src/main/scala/org/scalajs/dom/css.scala
src/main/scala/org/scalajs/dom/ext/Extensions.scala
src/main/scala/org/scalajs/dom/ext/KeyValue.scala
src/main/scala/org/scalajs/dom/ext/package.scala
src/main/scala/org/scalajs/dom/html.scala
src/main/scala/org/scalajs/dom/idb.scala
src/main/scala/org/scalajs/dom/package.scala
src/main/scala/org/scalajs/dom/raw/Css.scala
src/main/scala/org/scalajs/dom/raw/Html.scala
src/main/scala/org/scalajs/dom/raw/Idb.scala
src/main/scala/org/scalajs/dom/raw/Svg.scala
src/main/scala/org/scalajs/dom/raw/WebGL.scala
src/main/scala/org/scalajs/dom/raw/lib.scala
src/main/scala/org/scalajs/dom/svg.scala
src/main/scala/org/scalajs/dom/webgl.scala

- The raw "everything goes" namespace is now org.scalajs.dom.raw
- org.scalajs.dom.{css, html, idb, svg, webgl} namespaces contain un-prefixed versions of the things that start with their prefix. The `Element` suffix has also been dropped where possible
- org.scalajs.dom.extensions has been renamed to org.scalajs.dom.ext
- org.scalajs.dom itself contains all things in org.scalajs.dom.raw that aren't in any of the un-prefixed namespaces
Overall, this should accomplish a few things:
- Massively clean up org.scalajs.dom.*, since we've moved ~270 names into proper namespaces
- Make dealing with these names much easier, e.g. now `dom.HTMLTableCellElement` is just `html.TableCell`
- Make a clear separation between "all un-modified dom facades" and "re-organized nice-to-use dom facades", so …

Reorganize the org.scalajs.dom namespace into something saner

---

src/main/scala/org/scalajs/dom/ext/Extensions.scala

Or is this missing intentionally?

Add 'space' KeyCode to Extensions

---

src/main/scala/org/scalajs/dom/raw/lib.scala

i got the following error with current code
```scala
Uncaught scala.scalajs.runtime.UndefinedBehaviorError: An undefined behavior was detected: 1425095692856 is not an instance of java.lang.Integer ...
```
when i cast Position to js.Dynamic and then timestamp to Double it worked fine.

GeoLocation Position -> timestamp should be double

---

src/main/scala/org/scalajs/dom/raw/Html.scala

If we have an HTMLElement, then we know that the ownerDocument is
specifically an HTMLDocument, not a plain Document.  That's useful type
information, since you often want to use HTML-specific methods on it.

Narrow ownerDocument for HTML elements

---

src/main/scala/org/scalajs/dom/package.scala

We should also expose ClipboardEvent as dom.ClipboardEvent.

Expose ClipboardEvent in dom package

---

src/main/scala/org/scalajs/dom/crypto/Crypto.scala
src/main/scala/org/scalajs/dom/crypto/package.scala
src/main/scala/org/scalajs/dom/raw/lib.scala

Implements http://www.w3.org/TR/WebCryptoAPI/

Implement Web Cryptography API

---

src/main/scala/org/scalajs/dom/raw/WebGL.scala

Fixes a few issues with the type signatures of some WebGL calls:
`polygonOffset` was `(Int, Int) => Unit`, rather than `(Double, Double) => Unit`
`lineWidth` was `(Int) => Unit`, rather than `(Double) => Unit`
`texParameterf` was `(Int, Int, Int) => Unit`, rather than `(Int, Int, Double) => Unit`
Also cleaned up some incorrect parameter documentation, and further clarified internalformat/format.
I also tried (uncommitted) to prevent some scaladoc warnings in this file of the form "Could not find any member to link for "Float32Array", but for some reason (possibly because it's external to scala-js-dom?) even fully qualified names still issue a warning.  If anyone has any idea how to handle this correctly, I'll combine that into this PR, too, since this file got a little shouty since the …

Fix WebGL signatures.

---

src/main/scala/org/scalajs/dom/raw/WebGL.scala

One more silly signature issue.  Integer depths for a depth buffer clamped from 0..1 aren't very useful :)

Fix WebGL clearDepth signature

---

src/main/scala/org/scalajs/dom/raw/Html.scala
src/main/scala/org/scalajs/dom/raw/Svg.scala
src/main/scala/org/scalajs/dom/raw/lib.scala

Fixes the HTML DOM elements.
Note- this needs to be done for SVG too, but will take a little longer, since I am less familiar with SVG and will need to consult the spec.  I can address that in this PR if necessary.

Fix #127 - HTMLElements should be abstract classes

---

src/main/scala/org/scalajs/dom/package.scala

Unfortuntely, due to #121 we can't sensibly export this object without a *massive* reworking of the entire `org.scalajs.dom` package.
Might as well at least remove it for now, given anyone using this export will get surprising runtime errors.

Fix #94: Remove erroneous MutationObserverInit export

---

src/main/scala/org/scalajs/dom/raw/Html.scala

Not much to say, here.  Adds `HTMLImageElement.onload`.

Fix #132: Add Image onload

---

src/main/scala/org/scalajs/dom/raw/lib.scala

Also move it next to `innerHeight`, because it was randomly tucked away between some event handlers.

Fix Window.innerWidth to be a def

---

src/main/scala/org/scalajs/dom/raw/lib.scala

Fun fact- these are defined in the w3c spec as `unsigned long long`...
https://dvcs.w3.org/hg/webperf/raw-file/tip/specs/NavigationTiming/Overview.html#sec-navigation-timing-interface
Either way, `Int` is too small and so `Double` is the only sensible type we can ascribe here.

Fix #139: PerformanceTiming attributes should be Double

---

src/main/scala/org/scalajs/dom/raw/lib.scala

I write a js library, that converts scala Futures into javascript Promises. To instantiate a Promise within scala.js code it needs to be a class

Turn Promise trait into a class with executor constructor parameter.

---

src/main/scala/org/scalajs/dom/raw/lib.scala

`identifier` on the`Touch`class is specified as a `long` http://www.w3.org/TR/touch-events/#idl-def-Touch.  I'm seeing `UndefinedBehaviourError` under iOS safari when the identifier is outside the range of an Int.

Fix Touch identifier to be Double

---

src/main/scala/org/scalajs/dom/ext/Extensions.scala

This is important for implementations of `XMLHttpRequest` that make a difference between an empty string argument, and no argument, such as, reportedly, Android mobile.
This is an updated version of #151.

Use `null` by default for Ajax data, and map it to 0-arg send().

---

example/src/main/scala/example/Example.scala
src/main/scala/org/scalajs/dom/ext/Extensions.scala
src/main/scala/org/scalajs/dom/package.scala

This is a pretty major breaking change, as now `dom` does not extend `Window` anymore. This means that selecting fields of the window through `dom.someField` is broken. `dom.window.someField` should be explicitly used instead.
We explicitly expose `document` as `dom.document`, because lots of examples out there use it this way, and it seems reasonable to keep that use case.

Fix #121: Make the dom package object a Scala object, not a js.Any.

---

src/main/scala/org/scalajs/dom/raw/lib.scala

Page offsets are not necessarily Integer values. The following exception was thrown when I tried to access `pageYOffset`:
```
java.lang.ClassCastException: 525.6000125312809 is not an instance of java.lang.Integer
```

Window: `pageXOffset` and `pageYOffset` are Double

---

.travis.yml
build.sbt
project/build.sbt
src/main/scala/org/scalajs/dom/crypto/Crypto.scala
src/main/scala/org/scalajs/dom/crypto/package.scala
src/main/scala/org/scalajs/dom/experimental/Notification.scala
src/main/scala/org/scalajs/dom/experimental/Vibration.scala
src/main/scala/org/scalajs/dom/ext/Extensions.scala
src/main/scala/org/scalajs/dom/raw/Audio.scala
src/main/scala/org/scalajs/dom/raw/Css.scala
src/main/scala/org/scalajs/dom/raw/Html.scala
src/main/scala/org/scalajs/dom/raw/Idb.scala
src/main/scala/org/scalajs/dom/raw/Svg.scala
src/main/scala/org/scalajs/dom/raw/WebGL.scala
src/main/scala/org/scalajs/dom/raw/lib.scala

Fix #163: Bump Scala.js to 0.6.5 and @js.native everything.

---

src/main/scala/org/scalajs/dom/crypto/Crypto.scala
src/main/scala/org/scalajs/dom/crypto/package.scala

With these changes it is possible to code the [WebCrypto API signing example](http://www.w3.org/TR/WebCryptoAPI/#examples-signing) in the same style as the example fixing #166 
```scala
GlobalCrypto.crypto.subtle.generateKey(
RsaHashedKeyGenParams(
2048,
new Uint8Array(js.Array[Short](1,0,1)), //65537
HashAlgorithm.`SHA-256`),
false,
js.Array(KeyUsages.sign,KeyUsages.verify)
)
```

Fix #166: generateKeyApi not flexible enough.

---

readme/Index.scalatex

I suspect this out of date documentation caused #175 to be reported.
I'm unsure how to actually update the hosted pages (and won't have permissions anyway), so once merged can one of the admins ensure this is done?  Thanks.

Update readme to use the latest release of scala-js-dom

---

src/main/scala/org/scalajs/dom/crypto/Crypto.scala
src/main/scala/org/scalajs/dom/raw/Idb.scala

Implementing [HTTP-Signature](https://tools.ietf.org/html/draft-cavage-http-signatures-05) (see:   [KeyStore.scala](https://github.com/read-write-web/rww-scala-js/blob/7667bb1473fae1909c6503251e08f4a05287b577/src/main/scala/rww/store/KeyStore.scala)), I found the need for the CryptoKeyPair trait. 
During discussions to get that to work, I also discovered that a previous change of mine was mistaken.
And I found a documentation bug.

added CryptoKeyPair trait. Fix RsaHashedKeyGenParams

---

src/main/scala/org/scalajs/dom/experimental/Fetch.scala
src/main/scala/org/scalajs/dom/experimental/JSIterable.scala
src/main/scala/org/scalajs/dom/experimental/ServiceWorker.scala
src/main/scala/org/scalajs/dom/experimental/Stream.scala
src/main/scala/org/scalajs/dom/experimental/package.scala

I have been using the Fetch API for my [rww-scala-js akka branch](https://github.com/read-write-web/rww-scala-js/blob/6a24b5ffdf62b1d07542a178a912882e844c7b7c/src/main/scala/rww/store/WebResourceActor.scala). The code that I have tested and used works. So I thought I'd push this over before someone goes through the same work again.
Probably still a lot to be improved.
This would close https://github.com/scala-js/scala-js-dom/issues/167

Fix #167: Add Fetch API + Streams API

---

src/main/scala/org/scalajs/dom/raw/lib.scala

https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio

Add window.devicePixelRatio

---

src/main/scala/org/scalajs/dom/experimental/Notification.scala

Was getting an error when calling new Notification.  Changing it to the below JSName appears to fix the problem.

fix refrence in JSName to point to correct javascript object

---

src/main/scala/org/scalajs/dom/raw/lib.scala

MDN documentation is located here:
https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer/ready

Added ServiceWorkerContainer.ready

---

.travis.yml

Travis warning: 
> This job ran on our legacy infrastructure. Please read our docs on how to upgrade.
This PR let scala-js-dom builds run against the new infrastructure (wonder if it works, trying it with this PR). 
This should speed up the travis build.
Further steps could be to configure ivy caching (speeds up build and saves some mb traffic, avoid compiler facade recompilation).

upgrade to travis docker infrastructure

---

src/main/scala/org/scalajs/dom/raw/Html.scala

Calling `.disabled` on elements like `HTMLImageElement`, `HTMLDivElement`, `HTMLParagraphElement` type-checks and causes this nastiness (at least in Chrome):
```
Uncaught scala.scalajs.runtime.UndefinedBehaviorError:
An undefined behavior was detected: undefined is not an instance of java.lang.Boolean
```

Html.disabled can be undefined

---

src/main/scala/org/scalajs/dom/raw/lib.scala

... such that `foo.isInstanceOf[org.scalajs.dom.raw.File]` and `match ... case file: File ⇒` are supported.

Make File an abstract class

---

src/main/scala/org/scalajs/dom/raw/WebGL.scala

This has been tested against my current code and appears to now behave correctly under Safari as well as Chrome.  Also I found two enums that I'd apparently missed when initially creating the facade, so they've been added, too.

Fix #198: Make WebGL constants final vals to support Safari.

---

src/main/scala/org/scalajs/dom/package.scala

These disappeared from the dom package when we stopped using a js.native package object, so add them back to prevent needlessly breaking code in 0.9.0.

Add console back to the dom package.

---

src/main/scala/org/scalajs/dom/crypto/Crypto.scala

This PR is an outcome of this discussion: https://github.com/bblfish/scala-js-dom/commit/d0800da8fb13d14817d556dbce000df9f24e5211#commitcomment-15037842

Correct algorithm parameter types in SubtleCrypto interface

---

src/main/scala/org/scalajs/dom/experimental/push/PushManager.scala
src/main/scala/org/scalajs/dom/experimental/push/package.scala

I did not include any of the following:
* Any item marked deprecated in MDN.

Fix #184: Add support for the Push API

---

src/main/scala/org/scalajs/dom/experimental/gamepad/Gamepad.scala
src/main/scala/org/scalajs/dom/experimental/gamepad/package.scala

https://www.w3.org/TR/2015/WD-gamepad-20151217/

Add Gamepad API.

---

src/main/scala/org/scalajs/dom/raw/lib.scala

See: https://www.w3.org/TR/cssom-view/#extensions-to-the-window-interface
Note- this doesn't appear to be an issue in any current browser (I suppose viewports tend to be integer width in the underlying OS), but the spec does mention `Double`, not `Int`.

Make Window.innerWidth and innerHeight Double

---

src/main/scala/org/scalajs/dom/experimental/webgl/WebGLExtensions.scala
src/main/scala/org/scalajs/dom/experimental/webgl/extensions/Extensions.scala
src/main/scala/org/scalajs/dom/experimental/webgl/package.scala

This is a WIP WebGL extensions patch for general comment (actual facades currently untested).
1. Is the typing with case objects used here the most succinct way to do it?
2. Is returning `Option[ExtensionType]` in the `getExtension` pimp sensible, or should we just allow it to return `null` references?
3. Since WebGL exposes the `getExtension` method, should this even BE in `experimental`, or should we import this stuff in along with `org.scalajs.dom.webgl`? `getExtension`, by definition, is going to successfully return any given extension based on the combination of video driver version, browser version and operation system, so you really never know what will happen until you try it.

Add WebGL Extensions

---

src/main/scala/org/scalajs/dom/raw/Audio.scala

It seems that it is the way to go according to the [spec](https://www.w3.org/TR/webaudio/#widl-AudioBufferSourceNode-buffer).

un-deprecate AudioBufferSourceNode.buffer

---

src/main/scala/org/scalajs/dom/experimental/URL.scala

See https://url.spec.whatwg.org/#api and 
https://developer.mozilla.org/en-US/docs/Web/API/URL/URL

Add URL constructor

---

src/main/scala/org/scalajs/dom/raw/lib.scala

It's possible to select a file bigger than 2GB.

File size as Double

---

src/main/scala/org/scalajs/dom/raw/Html.scala

PR #193 changed the `disabled` property on `HTMLElement` from `Boolean` to `js.UndefOr[Boolean]`.
Actually, there is no `disabled` property defined on the `HTMLElement` interface:
https://html.spec.whatwg.org/multipage/dom.html#htmlelement
This property is instead defined on specific sub-interfaces. So far I found 9 of them in the one-page specification for HTML:
- HTMLInputElement : https://html.spec.whatwg.org/#htmlinputelement
- HTMLButtonElement : https://html.spec.whatwg.org/#htmlbuttonelement
- HTMLSelectElement : https://html.spec.whatwg.org/#htmlselectelement
- HTMLOptGroupElement : https://html.spec.whatwg.org/#htmloptgroupelement
- HTMLOptionElement : https://html.spec.whatwg.org/#htmloptionelement
- HTMLTextAreaElement : https://html.spec.whatwg.org/#htmltextareaelement
- …

Move the disabled property to specific interfaces

---

src/main/scala/org/scalajs/dom/ext/Extensions.scala

The ability to get a hex representation is crucial when working with `<input type="color" ... />`: https://scalafiddle.io/sf/NfAZ1AU/6

Add toHex to Color

---

src/main/scala/org/scalajs/dom/crypto/Crypto.scala
src/main/scala/org/scalajs/dom/experimental/Notification.scala
src/main/scala/org/scalajs/dom/experimental/Stream.scala
src/main/scala/org/scalajs/dom/experimental/URL.scala
src/main/scala/org/scalajs/dom/experimental/domparser/DOMParser.scala
src/main/scala/org/scalajs/dom/experimental/intl/package.scala
src/main/scala/org/scalajs/dom/experimental/mediastream/MediaStream.scala
src/main/scala/org/scalajs/dom/experimental/push/PushManager.scala
src/main/scala/org/scalajs/dom/experimental/push/package.scala
src/main/scala/org/scalajs/dom/experimental/serviceworkers/ServiceWorkers.scala
src/main/scala/org/scalajs/dom/experimental/webrtc/WebRTC.scala
src/main/scala/org/scalajs/dom/ext/Extensions.scala
src/main/scala/org/scalajs/dom/ext/package.scala
src/main/scala/org/scalajs/dom/raw/Audio.scala
src/main/scala/org/scalajs/dom/raw/Html.scala
src/main/scala/org/scalajs/dom/raw/lib.scala

Not setting up scalafmt in the repo per se because there are still a few "mistakes".

Reformattings prompted by scalafmt.

---

src/main/scala/org/scalajs/dom/raw/lib.scala

Fixes #249. I've updated scaladoc comments to the latest MDN documentation as well. #249 contains links to the correct specs.

Correct the type of DataTransfer#types.

---

src/main/scala/org/scalajs/dom/raw/lib.scala

Only the go() method should take a delta parameter, which should always be an Int

Fix #254: Correct signature of history navigation methods

---

src/main/scala/org/scalajs/dom/raw/Html.scala
src/main/scala/org/scalajs/dom/raw/lib.scala

See:
* https://developer.mozilla.org/en-US/docs/Web/API/Document
* https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableElement
* https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableRowElement
* https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement
* https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableSectionElement
* https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableCellElement
* https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement
* https://developer.mozilla.org/en-US/docs/Web/API/HTMLFieldSetElement
* https://developer.mozilla.org/en-US/docs/Web/API/HTMLObjectElement
* https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement
* https://developer.mozilla.org/en-US/docs/Web/API/HTMLTrackElement
* …

Use def for read-only properties.

---

src/main/scala/org/scalajs/dom/raw/lib.scala

Remove nullary removeAttribute() and getAttribute(). Both throw TypeError.

Remove nullary removeAttribute() and getAttribute().

---

src/main/scala/org/scalajs/dom/html.scala
src/main/scala/org/scalajs/dom/raw/Html.scala
src/main/scala/org/scalajs/dom/raw/lib.scala

I had to turn off fatal warnings because the type aliases refer to the deprecated types. It might be better to remove the type aliases entirely, or even skip deprecation and just remove the offending types and fields immediately.
See:
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/bgsound
* https://msdn.microsoft.com/en-us/library/windows/apps/hh965347.aspx
* https://developer.mozilla.org/en-US/docs/Web/API/window/setImmediate
* https://developer.mozilla.org/en-US/docs/Web/API/Window/clearImmediate
* https://developer.mozilla.org/en/docs/Web/API/Event/srcElement
* https://msdn.microsoft.com/en-us/library/hh869721(v=vs.85).aspx
* https://www.w3.org/TR/html5/obsolete.html
* https://developer.mozilla.org/en-US/docs/Web/API/HTMLFontElement

Deprecate some non-standard and obsolete types and fields.

---

src/main/scala/org/scalajs/dom/raw/Html.scala

See https://html.spec.whatwg.org/multipage/tables.html#the-table-element:concept-element-dom

HTMLTableElement.deleteRow() doesn’t have a default value.

---

src/main/scala/org/scalajs/dom/raw/lib.scala

…and Attr.
See:
* https://dom.spec.whatwg.org/#interface-node
* https://dom.spec.whatwg.org/#interface-element
* https://dom.spec.whatwg.org/#interface-attr
* https://developer.mozilla.org/en-US/docs/Web/API/Node/prefix

Node.prefix is read-only (and deprecated). Has been moved to Element …f

---

src/main/scala/org/scalajs/dom/raw/lib.scala

See https://xhr.spec.whatwg.org/#interface-xmlhttprequest

Add XMLHttpRequest.responseUrl. Fixes #111.

---

src/main/scala/org/scalajs/dom/raw/lib.scala

See https://dom.spec.whatwg.org/#interface-customevent

Fix type of CustomEvent detail attribute

---

src/main/scala/org/scalajs/dom/raw/WebGL.scala

I think this is correct, but in any event the original constant in the comments does not exist.

Updated misleading comments about which constant to reference.

---

.scalafix.conf
build.sbt
example/src/main/scala/example/Example.scala
project/build.sbt
readme/Index.scalatex
src/main/scala/org/scalajs/dom/experimental/Fetch.scala
src/main/scala/org/scalajs/dom/experimental/Notification.scala
src/main/scala/org/scalajs/dom/experimental/Stream.scala
src/main/scala/org/scalajs/dom/experimental/URL.scala
src/main/scala/org/scalajs/dom/experimental/deviceorientation/DeviceOrientation.scala
src/main/scala/org/scalajs/dom/experimental/domparser/DOMParser.scala
src/main/scala/org/scalajs/dom/experimental/gamepad/Gamepad.scala
src/main/scala/org/scalajs/dom/experimental/intl/Intl.scala
src/main/scala/org/scalajs/dom/experimental/mediastream/MediaStream.scala
src/main/scala/org/scalajs/dom/experimental/serviceworkers/ServiceWorkers.scala
src/main/scala/org/scalajs/dom/experimental/sharedworkers/SharedWorker.scala
src/main/scala/org/scalajs/dom/experimental/webrtc/WebRTC.scala
src/main/scala/org/scalajs/dom/raw/Audio.scala
src/main/scala/org/scalajs/dom/raw/Css.scala
src/main/scala/org/scalajs/dom/raw/Html.scala
src/main/scala/org/scalajs/dom/raw/Idb.scala
src/main/scala/org/scalajs/dom/raw/Svg.scala
src/main/scala/org/scalajs/dom/raw/WebGL.scala
src/main/scala/org/scalajs/dom/raw/WebWorkers.scala
src/main/scala/org/scalajs/dom/raw/lib.scala

This PR contains everything involved in upgrading to Scala.js 0.6.15, piecemeal.
The first commit does the upgrade itself, and configures the compiler to ignore warnings related to major deprecations.
The next 3 commits use [scalafix](https://scalacenter.github.io/scalafix/) to automatically migrate facades to using `@JSGlobal`.
The last commit migrates the examples to use `@JSExportTopLevel` instead of `@JSExport` on top-level objects.

Upgrade to Scala.js 0.6.15.

---

src/main/scala/org/scalajs/dom/package.scala
src/main/scala/org/scalajs/dom/raw/lib.scala

Fixes run time error where constructor argument(s) were expected but compile time required a nullary constructor.

Align KeyboardEvent constructor to spec; add KeyboardEventInit helper

---

src/main/scala/org/scalajs/dom/experimental/permissions/package.scala

Supported in Chrome and Firefox. https://developer.mozilla.org/en-US/docs/Web/API/Permissions
Not complete, but usable. 
Example usage:
`navigator.permissions.query(js.Dynamic.literal(name = "geolocation")).toFuture`

Add basic support for the Permissions API

---

src/main/scala/org/scalajs/dom/raw/Html.scala

According to [HTMLInputElement on MDN](https://developer.mozilla.org/de/docs/Web/API/HTMLInputElement#Properties), `valueAsNumber` returns a `Double`.

HTMLInputElement.valueAsNumber returns Double

---

src/main/scala/org/scalajs/dom/raw/lib.scala

In Firefox 58 and Chromium 64, a KeyboardEvent's `locale` property
returns `undefined`.
See also https://bugs.chromium.org/p/chromium/issues/detail?id=168971#c25

KeyboardEvent: Remove `locale`

---

src/main/scala/org/scalajs/dom/raw/lib.scala

The pull request https://github.com/scala-js/scala-js-dom/pull/64 already attempted to add the `contains()` method, but it does not seem to have been merged. `contains()` is now widely supported by browsers and I presume it is safe to add this function.
See also:
- https://developer.mozilla.org/en-US/docs/Web/API/Node/contains
- https://dom.spec.whatwg.org/#dom-node-contains-other-other

Node: Add contains()

---

src/main/scala/org/scalajs/dom/raw/lib.scala

At the moment, all `getElementsBy*` functions return a `NodeList`, but the items are guaranteed to be `Element`s. Therefore, to access an item as an `Element`, a cast is required.
Furthermore, I would propose to remove the function `getElementsByName()` which does not appear in the DOM interfaces and seems to have been superseded by `getElementsByTagName()`. If you agree, I will add a separate commit for it to this pull request. 
See also:
- https://dom.spec.whatwg.org/#document
- https://dom.spec.whatwg.org/#element

Return HTMLCollection in getElementsBy*()

---

src/main/scala/org/scalajs/dom/raw/lib.scala

This pull request deprecates https://github.com/scala-js/scala-js-dom/pull/220.

Clipboard events: Fix signatures and add comments

---

src/main/scala/org/scalajs/dom/ext/Extensions.scala
src/main/scala/org/scalajs/dom/raw/lib.scala

The current naming of the object `KeyboardEvent` is slightly unfortunate as it only contains constants related to key locations.
Other wrappers call this object `KeyLocation`:
* https://api.dartlang.org/stable/1.24.3/dart-html/KeyLocation-class.html
* https://vaadin.com/api/7.6.5/elemental/events/KeyboardEvent.KeyLocation.html
For compatibility reasons, I kept the object and defined aliases in `ext`.
I was also considering to drop `js.native` since the standard defines the constants as follows: 
```scala
val DOM_KEY_LOCATION_STANDARD = 0x00
val DOM_KEY_LOCATION_LEFT     = 0x01
val DOM_KEY_LOCATION_RIGHT    = 0x02
val DOM_KEY_LOCATION_NUMPAD   = 0x03
```

Improve DOM_KEY_LOCATION_* bindings

---

src/main/scala/org/scalajs/dom/experimental/serviceworkers/ServiceWorkers.scala

Specification:
- [showNotification](https://notifications.spec.whatwg.org/#dom-serviceworkerregistration-shownotification)
- [getNotifications](https://notifications.spec.whatwg.org/#dom-serviceworkerregistration-getnotifications)

Add showNotification/getNotifications to ServiceWorkerRegistration

---

src/main/scala/org/scalajs/dom/experimental/push/PushManager.scala

Link to [specification](https://w3c.github.io/push-api/#dom-pushsubscriptionoptions-applicationserverkey)

Add applicationServerKey to PushSubscriptionOptions

---

src/main/scala/org/scalajs/dom/experimental/webrtc/package.scala

The `navigator.getUserMedia()` method is [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/getUserMedia), and in fact during [our hackday](https://twitter.com/rtyley/status/1067815067780087808), I found that I could gain Firefox support just by using the `navigator.mediaDevices.getUserMedia()` method instead, which is [documented](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#Browser_compatibility
) as having good cross-browser support. The deprecation seems to have occurred around [28th May 2014](https://github.com/w3c/mediacapture-main/commit/de3bdaf83d2cc1350cc3be970baf1d11219add1d#diff-ea76d38900f79cfae8f60e5f7cf16dd1R2755).

Add `navigator.mediaDevices.getUserMedia()`, deprecate old method

---

src/main/scala/org/scalajs/dom/raw/Svg.scala

``def getComputedTextLength(): Int = js.native``
should be 
def getComputedTextLength(): Double = js.native
https://developer.mozilla.org/en-US/docs/Web/API/SVGTextContentElement

Fix the result type of a few methods in SVGTextContentElement to Double.

---

src/main/scala/org/scalajs/dom/raw/lib.scala

Alternatively, this could be implemented as a polyfill for older browser support, but I don't think scala-js does anything with a polyfill, correct?

Add Element.matches which has all modern browser support

---

src/main/scala/org/scalajs/dom/experimental/AbortController.scala
src/main/scala/org/scalajs/dom/experimental/Fetch.scala

Add AbortController and AbortSignal classes along with adding `signal`
to the Fetch request classes. In addition also add `keepalive` to Fetch
request and fix the names of the `cache` and `redirect` properties.

Add types for AbortController

---

src/main/scala/org/scalajs/dom/experimental/push/PushManager.scala

Update PushSubscription to better reflect w3 standards:
-Change the return type of method toJSON
-Add missing properties (expirationTime, options)
Disclosure I have no idea what I'm doing here or if this is event a problem for anyone else.
(The impression that I have is that if any one is calling this method this will throw a cast extension)
This PR fix my problem but I don't know if this `js.Dictionary[js.Any] ` is the right type, and maybe could be better refine. (https://www.w3.org/TR/2018/WD-push-api-20181026/#idl-def-pushsubscriptionoptionsinit)

Fix #346: Give the correct type to PushSubscription.toJSON

---

src/main/scala/org/scalajs/dom/raw/lib.scala

This Pull Request adds an implementation for passing an options object to `addEventListener`.  
The three options in that object allow for more control about how an event-listener behaves and can be quite useful, especially when working with touchscreen devices.  
The documentation was provided by MDN, details about the standard can be read here:  
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Parameters  
The standard is supported by all *major* browsers, with the only exception being IE11.
https://caniuse.com/#feat=passive-event-listener

Add overloads of {add,remove}EventListener with options objects

---

src/main/scala/org/scalajs/dom/raw/Html.scala

Fix #327: Add HTMLElement.dataset

---

src/main/scala/org/scalajs/dom/raw/lib.scala

Closes #354 
* https://caniuse.com/#feat=page-transition-events Supported by all major browsers except Opera Mini  
* https://developer.mozilla.org/en-US/docs/Web/API/PageTransitionEvent
* https://developer.mozilla.org/en-US/docs/Web/API/Window/pageshow_event
* https://developer.mozilla.org/en-US/docs/Web/API/Window/pagehide_event

Fix #354: Add PageTransitionEvent and corresponding event handler properties.

---

src/main/scala/org/scalajs/dom/raw/lib.scala

Add dirxml, debug, table, trace, time, timeEnd, count, countReset, group, groupCollapsed, and groupEnd.

Add missing methods to Console

---

src/main/scala/org/scalajs/dom/html.scala
src/main/scala/org/scalajs/dom/raw/Html.scala

Mark deprecated/non-standard HTMLElement interfaces as deprecated

---

src/main/scala/org/scalajs/dom/ext/Extensions.scala

Fixed the below compile error.
```
[error] /home/vagrant/IdeaProjects/scala-js-dom/src/main/scala/org/scalajs/dom/ext/Extensions.scala:279:33: ambiguous reference to overloaded definition,
[error] both method position in class ByteBuffer of type (x$1: Int)java.nio.ByteBuffer
[error] and  method position in class Buffer of type ()Int
[error] match expected type ?
[error]         val origPosition = data.position
[error]                                 ^
```

Fix ambiguous reference to overloaded definition

---

src/main/scala/org/scalajs/dom/experimental/URL.scala
src/main/scala/org/scalajs/dom/ext/Extensions.scala

Closes #339 
[URLSearch​Params](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) is [widely-adopted](https://caniuse.com/#feat=urlsearchparams) standard.

Add URL.searchParams (URLSearch​Params)

---

src/main/scala/org/scalajs/dom/experimental/deviceorientation/DeviceOrientation.scala
src/main/scala/org/scalajs/dom/experimental/gamepad/Gamepad.scala
src/main/scala/org/scalajs/dom/experimental/mediastream/MediaStream.scala
src/main/scala/org/scalajs/dom/experimental/serviceworkers/ServiceWorkers.scala
src/main/scala/org/scalajs/dom/experimental/webrtc/WebRTC.scala
src/main/scala/org/scalajs/dom/raw/Idb.scala
src/main/scala/org/scalajs/dom/raw/Svg.scala
src/main/scala/org/scalajs/dom/raw/lib.scala
src/main/scala/org/scalajs/dom/svg.scala

Closes #219
* Add valid constructors that accept type name and init, as well as type-safe constructor options `***EventInit`
* Removes invalid default (0 args) constructors since `new ***Event()` raises RuntimeError due to lack of required argument
* Add `@deprecated` based on MDN

Fix #219: Fix Event constructors.

---

.travis.yml

It seems that Travis no longer install `oraclejdk8` (then [build fails](https://travis-ci.org/scala-js/scala-js-dom/jobs/545496915#L165)) so let's use `openjdk8`.
[As of  2019-04-15, `xenial` is now default and recommended on Travis](https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment), so let's move on instead of staying `trusty`. 
This PR explicitly specifies `xenial`, so it won't be updated to latest silently and break builds in future.
And [`sudo: false` is no longer be available](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration) so let's drop it.

Fix Travis JDK8 installation failure

---

src/main/scala/org/scalajs/dom/experimental/URL.scala

According to the documentation
https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/get#Return_value
URLSearchParams.get will return null but not undefined when the parameter is not found.

Fix the return type of URLSearchParams.get

---

src/main/scala/org/scalajs/dom/experimental/intl/Intl.scala

According to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Collator

Fix wrong parameter names in CollatorOptions

---

src/main/scala/org/scalajs/dom/experimental/storage/package.scala

Closes #377 
https://storage.spec.whatwg.org/
Chrome and Firefox have implemented
https://developer.mozilla.org/en-US/docs/Web/API/Storage_API#Browser_compatibility

Add experimental Storage API support.

---

build.sbt
src/main/scala/org/scalajs/dom/experimental/Fetch.scala
src/main/scala/org/scalajs/dom/experimental/deviceorientation/DeviceOrientation.scala
src/main/scala/org/scalajs/dom/experimental/gamepad/Gamepad.scala
src/main/scala/org/scalajs/dom/experimental/mediastream/MediaStream.scala
src/main/scala/org/scalajs/dom/experimental/push/PushManager.scala
src/main/scala/org/scalajs/dom/experimental/serviceworkers/ServiceWorkers.scala
src/main/scala/org/scalajs/dom/experimental/webrtc/WebRTC.scala
src/main/scala/org/scalajs/dom/experimental/webrtc/package.scala
src/main/scala/org/scalajs/dom/ext/Extensions.scala
src/main/scala/org/scalajs/dom/ext/package.scala
src/main/scala/org/scalajs/dom/html.scala
src/main/scala/org/scalajs/dom/package.scala
src/main/scala/org/scalajs/dom/raw/Audio.scala
src/main/scala/org/scalajs/dom/raw/Html.scala
src/main/scala/org/scalajs/dom/raw/Svg.scala
src/main/scala/org/scalajs/dom/raw/lib.scala
src/main/scala/org/scalajs/dom/raw/package.scala
src/main/scala/org/scalajs/dom/svg.scala

* Bump the version number to 1.0.0-SNAPSHOT
* Remove all the deprecated things

Prepare for version 1.0.0.

---

src/main/scala/org/scalajs/dom/raw/lib.scala

https://developer.mozilla.org/en-US/docs/Web/API/Clipboard
This PR adds `Clipboard` trait.
It's instance can be obtained via `Navigator.clipboard` property.

Add Clipboard API

---

src/main/scala/org/scalajs/dom/raw/lib.scala

Fix #376: Add the Fullscreen API

---

src/main/scala/org/scalajs/dom/experimental/Fetch.scala

This way, users do not have to recite every field when creating a `RequestInit`. Also, the spec says the `RequestInit` dictionary must contain a field `window` which is set to null. We might as well include this too as a final variable, since the spec shows omitting it should be a type error.
Prompted by gitter conversation here: https://gitter.im/scala-js/scala-js?at=5d80415105fd3716953afa47

Make the fields of RequestInit optional.

---

src/main/scala/org/scalajs/dom/raw/lib.scala

According to MDN https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent, `CustomEventInit` accept `"detail"` field, not `"detailArg"`.

Fix CustomEventInit field name

---

src/main/scala/org/scalajs/dom/ext/Extensions.scala

For some reason Patch is absent in Ajax. THe following PR fixes this problem.

Add REST method PATCH for Ajax

---

.github/workflows/ghpages.yml

Fixes #178  
As per [the docs](https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow#about-the-github_token-secret) the `secrets.GITHUB_TOKEN` is magically added by a Github Action.  
So it should *just work*™ .
I did try this with [one of my own projects](https://github.com/sake92/hepek/runs/1219699979?check_suite_focus=true) and it works fine! :)

Add ghpages github action

---

example/src/main/scala/example/Example.scala
readme/Index.scalatex

Improvements:
- openweathermap didnt work (needs an API key), so I used another free API :D
- websockets didnt work when using https, it has to be wss (secure socket)..
- 2 cosmetic changes

Fix docs examples

---

build.sbt

So that we can release v2.0.0 with the Scala 3 artifact.
Fixes #451.

Bump to 2.0.0-SNAPSHOT.

---

.github/workflows/ci.yml
build.sbt

And therefore for Scala 2.10.x.

Drop support for Scala.js 0.6.x.

---

.github/workflows/ci.yml
build.sbt

Those are the reference versions for Scala.js 1.5.0, which we use, so they make the most sense. See
https://github.com/scala-js/scala-js/blob/v1.5.0/project/MultiScalaProject.scala#L80-L84

Upgrade to Scala 2.12.12 and 2.13.4.

---

.github/release-drafter.yml
.github/workflows/release-drafter.yml
.github/workflows/release.yml
build.sbt
project/plugins.sbt

Who could argue that sbt-gh-actions is preferable to this!! :P

Setup CI release

---

api-reports/2_12.txt
api-reports/2_13.txt
src/main/scala/org/scalajs/dom/raw/lib.scala

- Add moveTo and moveBy to Window
- Add resizeTo and resizeBy to Window
- Add scrollX and scrollY to Window
- Undo addition of CanvasRenderingContext2D.moveBy
Sorry for the previous PR, it was hastily made.
I also used Int as arguments type for window position related functions (in line with https://github.com/purescript-web/purescript-web-html API). Window positions are integers across all operating systems.
Maybe you can keep this PR open and I can add other missing functions and properties? I'm going through them right now.

Add moveTo and moveBy to Window

---

.github/workflows/release.yml

I hope this works, it's a really sticky situation because `sbt-ci-release` wants to release all crosses at once.
Fixes #477

Add 2.10 hack to release.yml

---

build.sbt

I'm not sure what was used in the `0.x` stage of this project, so I'm specifying `semver-spec` and not `early-semver` to be cautious, doubt it'll matter to anyone.

Set version scheme for publishing

---

api-reports/2_12.txt
api-reports/2_13.txt
src/main/scala/org/scalajs/dom/css.scala
src/main/scala/org/scalajs/dom/raw/Css.scala

https://developer.mozilla.org/en-US/docs/Web/API/CSS/supports

Fix #489 Add CSS.supports

---

api-reports/2_12.txt
api-reports/2_13.txt
src/main/scala/org/scalajs/dom/raw/Html.scala

https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/play
The spec says:
> Browsers released before 2019 may not return a value from `play()`
So I made the return value `js.UndefOr[js.Promise[Unit]]`.

Fix #488 `HTMLMediaElement.play()` should return `Promise`

---

api-reports/2_12.txt
api-reports/2_13.txt
src/main/scala/org/scalajs/dom/experimental/serviceworkers/ServiceWorkers.scala

Cropped up in https://github.com/http4s/http4s/pull/5089.
https://developer.mozilla.org/en-US/docs/Web/API/FetchEvent/preloadResponse#value

Fix return type of `FetchEvent.preloadResponse`

---

api-reports/2_12.txt
api-reports/2_13.txt
src/main/scala/org/scalajs/dom/experimental/Stream.scala

https://streams.spec.whatwg.org/#rs-class-definition
https://streams.spec.whatwg.org/#ws-class-definition
Useful for https://github.com/http4s/http4s/pull/5103.

Make reason for Readable/WritableStream cancel/abort optional

---

.github/workflows/ci.yml
.github/workflows/ghpages.yml
.github/workflows/release.yml

Which makes use of the brand new GitHub Actions feature: action
composition. This allows us to just have a single GHA for everything
Scala and Scala.JS, and centralise and hide boring details like caching.

Use GitHub Action: japgolly/setup-everything-scala

---

api-reports/2_12.txt
api-reports/2_13.txt
src/main/scala/org/scalajs/dom/raw/lib.scala

MDN Documentation: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/imageSmoothingEnabled

Add CanvasRenderingContext2D.imageSmoothingEnabled

---

api-reports/2_12.txt
api-reports/2_13.txt
scalafix/src/main/scala/org/scalajs/dom/scalafix/Util.scala

Dealias types when collecting parents

---

build.sbt

Will fix #524.
Currently fails with:
> To use Scalafix on Scala 3 projects, you must unset `scalafixBinaryScalaVersion`. Rules such as ExplicitResultTypes requiring the project version to match the Scalafix version are unsupported for the moment.

Restore scalafix task to prePR

---

.github/workflows/ci.yml
api-reports/2_12.txt
api-reports/2_13.txt
build.sbt
project/plugins.sbt

Also `prePR` needed another run after yesterday's fix

Upgrade Scala.js and Scala

---

.github/workflows/ci.yml
build.sbt
prePR.sbt
project/Build.scala
project/Lib.scala
project/plugins.sbt
tests-chrome/src/test/scala/org/scalajs/dom/tests/chrome/ChromeTests.scala
tests-firefox/src/test/scala/org/scalajs/dom/tests/firefox/FirefoxTests.scala
tests-node-jsdom/src/test/scala/org/scalajs/dom/tests/node/jsdom/NodeJsdomTests.scala
tests-shared/src/main/scala/org/scalajs/dom/tests/shared/AsyncTesting.scala
tests-shared/src/main/scala/org/scalajs/dom/tests/shared/SharedTests.scala
tests-webworker/src/main/scala/org/scalajs/dom/tests/webworker/Client.scala
tests-webworker/src/main/scala/org/scalajs/dom/tests/webworker/Protocol.scala
tests-webworker/src/main/scala/org/scalajs/dom/tests/webworker/Server.scala
tests-webworker/src/main/scala/org/scalajs/dom/tests/webworker/WebWorkerTests.scala

Add tests for {node + jsdom, chrome, firefox, webworkers}

---

api-reports/2_12.txt
api-reports/2_13.txt
src/main/scala/org/scalajs/dom/IDBTypes.scala
src/main/scala/org/scalajs/dom/idb.scala
src/main/scala/org/scalajs/dom/raw.scala

IDB DomString constants have been removed from browser API and replaced by raw String values.
Remove IDB DOMString constants that are no more supported and lead to an UndefinedBehaviorError.
Add these constants in a typesafe way.

feat(idb): Update to newer API

---

tests-shared/src/main/scala/org/scalajs/dom/tests/shared/SharedTests.scala

This confirms that #371 is no longer needed.

Test that DOMTokenList acts like a Seq

---

.scalafix.conf
api-reports/2_12.txt
api-reports/2_13.txt
prePR.sbt
src/main/scala/org/scalajs/dom/Fetch.scala
src/main/scala/org/scalajs/dom/IDBTypes.scala
src/main/scala/org/scalajs/dom/Stream.scala
src/main/scala/org/scalajs/dom/crypto/Crypto.scala
src/main/scala/org/scalajs/dom/experimental/gamepad/package.scala
src/main/scala/org/scalajs/dom/experimental/mediastream/MediaStream.scala
src/main/scala/org/scalajs/dom/experimental/permissions/package.scala
src/main/scala/org/scalajs/dom/experimental/push/PushManager.scala
src/main/scala/org/scalajs/dom/experimental/serviceworkers/ServiceWorkers.scala
src/main/scala/org/scalajs/dom/experimental/webrtc/WebRTC.scala
src/main/scala/org/scalajs/dom/ext/Extensions.scala
src/main/scala/org/scalajs/dom/lib.scala

Enable ExplicitResultTypes

---

api-reports/2_12.txt
api-reports/2_13.txt
src/main/scala/org/scalajs/dom/lib.scala

https://w3c.github.io/FileAPI/#blob-section

Fix #515 Blob.stream() emits Uint8Array

---

api-reports/2_12.txt
api-reports/2_13.txt
src/main/scala/org/scalajs/dom/WebWorkerTypes.scala
src/main/scala/org/scalajs/dom/experimental/serviceworkers/ServiceWorkers.scala
src/main/scala/org/scalajs/dom/lib.scala

Revise all `postMessage` methods

---

api-reports/2_12.txt
api-reports/2_13.txt
src/main/scala/org/scalajs/dom/WebWorkerTypes.scala
src/main/scala/org/scalajs/dom/beacon.scala
src/main/scala/org/scalajs/dom/experimental/beacon/package.scala
src/main/scala/org/scalajs/dom/lib.scala

Towards #545. Tried my hand at this but kind of tricky to do while maintaining source compatibility, let me know what you think, thanks!

Migrate beacon to dom

---

.scalafix.conf
api-reports/2_12.txt
api-reports/2_13.txt
prePR.sbt
scalafix/src/main/resources/META-INF/services/scalafix.v1.Rule
scalafix/src/main/scala/org/scalajs/dom/scalafix/DefaultFacadeArgs.scala
scalafix/src/main/scala/org/scalajs/dom/scalafix/GenerateApiReport.scala
scalafix/src/main/scala/org/scalajs/dom/scalafix/Util.scala
src/main/scala/org/scalajs/dom/Audio.scala
src/main/scala/org/scalajs/dom/Fetch.scala
src/main/scala/org/scalajs/dom/IDBTypes.scala
src/main/scala/org/scalajs/dom/OffscreenCanvas.scala
src/main/scala/org/scalajs/dom/Stream.scala
src/main/scala/org/scalajs/dom/WindowOrWorkerGlobalScope.scala
src/main/scala/org/scalajs/dom/beacon.scala
src/main/scala/org/scalajs/dom/experimental/serviceworkers/ServiceWorkers.scala
src/main/scala/org/scalajs/dom/lib.scala

Default args for facades should be `js.native`

---

api-reports/validate

It stopped working because we stopped regenerating the api reports from CI.
Follow up to #567

Fix api report validation

---

api-reports/2_12.txt
api-reports/2_13.txt
src/main/scala/org/scalajs/dom/CacheStorage.scala
src/main/scala/org/scalajs/dom/WindowOrWorkerGlobalScope.scala
src/main/scala/org/scalajs/dom/experimental/cachestorage/package.scala

Migrate CacheStorage to dom

---

api-reports/2_12.txt
api-reports/2_13.txt
src/main/scala/org/scalajs/dom/Gamepad.scala
src/main/scala/org/scalajs/dom/experimental/gamepad/package.scala
src/main/scala/org/scalajs/dom/lib.scala

Migrate Gamepad to dom

---

api-reports/2_12.txt
api-reports/2_13.txt
src/main/scala/org/scalajs/dom/experimental/storage/package.scala
src/main/scala/org/scalajs/dom/lib.scala
src/main/scala/org/scalajs/dom/storage.scala

Migrate storage to dom

---

api-reports/2_12.txt
api-reports/2_13.txt
src/main/scala/org/scalajs/dom/FileReaderSync.scala
src/main/scala/org/scalajs/dom/experimental/package.scala

Migrate FileReaderSync to dom

---

api-reports/2_12.txt
api-reports/2_13.txt
src/main/scala/org/scalajs/dom/Notification.scala
src/main/scala/org/scalajs/dom/crypto/Crypto.scala
src/main/scala/org/scalajs/dom/experimental/intl/Intl.scala
src/main/scala/org/scalajs/dom/experimental/mediastream/MediaStream.scala
src/main/scala/org/scalajs/dom/experimental/permissions/package.scala
src/main/scala/org/scalajs/dom/experimental/webrtc/WebRTC.scala
src/main/scala/org/scalajs/dom/lib.scala

And deprecate all the `def apply`-based constructors, in favor of the `new Foo { ... }` syntax.

Clean up config traits

---

api-reports/2_12.txt
api-reports/2_13.txt
src/main/scala/org/scalajs/dom/package.scala

Closes #597
I orginally thought the type would be js.UndefOr[Crypto] but according
to MDN, `crypto` is always available but not all of the methods are.

Add `webcrypto`

---

api-reports/2_12.txt
api-reports/2_13.txt
dom/src/main/scala/org/scalajs/dom/ReadableStream.scala

Nice to meet you!
According to [the whatwg spec](https://streams.spec.whatwg.org/#rs-class-definition), `ReadableStream#pipeTo` should return a `Promise<undefined>`. This PR modifies the binding to return `js.Promise[Unit]` instead of a plain `Unit`.

Change ReadableStream#pipeTo to return js.Promise[Unit]

---

api-reports/2_12.txt
api-reports/2_13.txt
dom/src/main/scala/org/scalajs/dom/DeviceMotionEventInit.scala
dom/src/main/scala/org/scalajs/dom/FocusEventInit.scala
dom/src/main/scala/org/scalajs/dom/GamepadEventInit.scala
dom/src/main/scala/org/scalajs/dom/ResponseInit.scala
dom/src/main/scala/org/scalajs/dom/UIEventInit.scala
dom/src/main/scala/org/scalajs/dom/experimental/package.scala

Fixes #624. I went through all of the -`Init` classes and checked that they are using `var` and `js.undefined` as their default value. Are there non-`Init` classes that we should check too?

Always use `var` and `undefined` for `new`-based constructors

---

api-reports/2_12.txt
api-reports/2_13.txt
dom/src/main/scala-2/org/scalajs/dom/WorkerType.scala
dom/src/main/scala-3/org/scalajs/dom/WorkerType.scala
dom/src/main/scala/org/scalajs/dom/SharedWorker.scala
dom/src/main/scala/org/scalajs/dom/Worker.scala
dom/src/main/scala/org/scalajs/dom/WorkerOptions.scala

https://developer.mozilla.org/en-US/docs/Web/API/Worker/Worker
https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker/SharedWorker

Add `WorkerOptions` to [Shared]Worker constructors

---

api-reports/2_12.txt
api-reports/2_13.txt
dom/src/main/scala-2/org/scalajs/dom/ResizeObserverBoxOption.scala
dom/src/main/scala-3/org/scalajs/dom/ResizeObserverBoxOption.scala
dom/src/main/scala/org/scalajs/dom/DOMRect.scala
dom/src/main/scala/org/scalajs/dom/DOMRectReadOnly.scala
dom/src/main/scala/org/scalajs/dom/ResizeObserver.scala
dom/src/main/scala/org/scalajs/dom/ResizeObserverEntry.scala
dom/src/main/scala/org/scalajs/dom/ResizeObserverOptions.scala
dom/src/main/scala/org/scalajs/dom/ResizeObserverSize.scala

Mozilla Docs : https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver
Similar to [MutationObserver](https://github.com/scala-js/scala-js-dom/blob/main/dom/src/main/scala/org/scalajs/dom/MutationObserver.scala)
I wasn't sure about adding [ResizeObserverEntry.devicePixelContentBoxSize](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserverEntry/devicePixelContentBoxSize), since as of now it isn't supported by Safari. I decided to leave out, but I would be happy to add it into this PR.
I also added [DOMRectReadOnly](https://developer.mozilla.org/en-US/docs/Web/API/DOMRectReadOnly), which seems a bit out of place in this PR but a few of the interfaces require that type. I'm also a bit concerned about adding it in this state due to the already implemented …

Add Façade Types to Support ResizeObserver

---

api-reports/2_12.txt
api-reports/2_13.txt
dom/src/main/scala/org/scalajs/dom/HTMLButtonElement.scala
dom/src/main/scala/org/scalajs/dom/HTMLFieldSetElement.scala
dom/src/main/scala/org/scalajs/dom/HTMLFormElement.scala
dom/src/main/scala/org/scalajs/dom/HTMLInputElement.scala
dom/src/main/scala/org/scalajs/dom/HTMLObjectElement.scala
dom/src/main/scala/org/scalajs/dom/HTMLSelectElement.scala
dom/src/main/scala/org/scalajs/dom/HTMLTextAreaElement.scala

`setCustomValidity`s error message is shown only when `reportValidity`
is called afterwards.
See https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/setCustomValidity
for example.

Add report validity facade method

---

api-reports/2_12.txt
api-reports/2_13.txt
dom/src/main/scala-2/org/scalajs/dom/ServiceWorkerUpdateViaCache.scala
dom/src/main/scala-3/org/scalajs/dom/ServiceWorkerUpdateViaCache.scala
dom/src/main/scala/org/scalajs/dom/ServiceWorkerContainer.scala
dom/src/main/scala/org/scalajs/dom/ServiceWorkerRegistrationOptions.scala

https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer/register

Add `ServiceWorkerRegistrationOptions`

---

api-reports/2_12.txt
api-reports/2_13.txt
dom/src/main/scala/org/scalajs/dom/EventSource.scala
dom/src/main/scala/org/scalajs/dom/EventSourceInit.scala

https://developer.mozilla.org/en-US/docs/Web/API/EventSource/EventSource

Add `EventSourceInit`

---

api-reports/2_12.txt
api-reports/2_13.txt
dom/src/main/scala/org/scalajs/dom/IDBStoreLike.scala

Ref:
* https://microsoft.github.io/PowerBI-JavaScript/interfaces/_node_modules_typedoc_node_modules_typescript_lib_lib_dom_d_.idbobjectstore.html#opencursor
* https://developer.mozilla.org/en-US/docs/Web/API/IDBObjectStore/openKeyCursor
* https://developer.mozilla.org/en-US/docs/Web/API/IDBObjectStore/openCursor

IDB cursor result types were incorrectly abstract

---

readme/Index.scalatex

Not sure the support is still correct, but I added Scala 3.0 and 3.1

Update Index.scalatex to use version 2.2.0

---

api-reports/2_12.txt
api-reports/2_13.txt
dom/src/main/scala/org/scalajs/dom/package.scala

I am very glad URLSearchParams already existed...

Add `URLSearchParams` to `BodyInit`

---

api-reports/2_12.txt
api-reports/2_13.txt
dom/src/main/scala/org/scalajs/dom/Element.scala

https://developer.mozilla.org/en-US/docs/Web/API/Element/replaceWith
Let me know what you think!

Add `Element#replaceWith`

---

api-reports/2_12.txt
api-reports/2_13.txt
dom/src/main/scala/org/scalajs/dom/MediaQueryList.scala
dom/src/main/scala/org/scalajs/dom/MediaQueryListListener.scala

It would seem that MediaQueryList was outdated, so I updated it according to the MDN: https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList
The main difference is that now MediaQueryList extends EventTarget which allows for `addEventListener` method and others. Deprecated `addListener` and `removeListener` methods. ~~I hope that I got the version number for @deprecated right.~~
I could not get the compiler to compile with `addListener` because it expected `MediaQueryListListener`. Don't know if this has ever worked for someone. I am very new to scala and maybe I don't know how it was supposed to work.
```scala
val prefersDark: MediaQueryList = window.matchMedia("(prefers-color-scheme: dark)")
prefersDark.addListener({ (e: MediaQueryList) =>
println(e.matches)
})
```
would …

Updates MediaQueryList to extend EventTarget

---

api-reports/2_12.txt
api-reports/2_13.txt
dom/src/main/scala/org/scalajs/dom/KeyboardEvent.scala
dom/src/main/scala/org/scalajs/dom/KeyboardEventInit.scala

Hi @armanbilge, here is the PR for the issue https://github.com/scala-js/scala-js-dom/issues/726.

Add `KeyboardEvent#code`

---

api-reports/2_12.txt
api-reports/2_13.txt
dom/src/main/scala-2/org/scalajs/dom/PresentationStyle.scala
dom/src/main/scala-3/org/scalajs/dom/PresentationStyle.scala
dom/src/main/scala/org/scalajs/dom/Clipboard.scala
dom/src/main/scala/org/scalajs/dom/ClipboardItem.scala
dom/src/main/scala/org/scalajs/dom/ClipboardItemOptions.scala
dom/src/main/scala/org/scalajs/dom/FrozenArray.scala
dom/src/main/scala/org/scalajs/dom/package.scala

I probably missed something, let me know what can be improved!

Fixup `Clipboard` to use added `ClipboardItem`

---

dom/src/main/scala/org/scalajs/dom/Body.scala

The spec uses `js.Any` there anyway and I see no real compelling reason to change it. The "`JSON`" type is just a POJSO plain-old-javascript-object.
https://fetch.spec.whatwg.org/#body

Remove stale todo

---

api-reports/2_12.txt
api-reports/2_13.txt
dom/src/main/scala/org/scalajs/dom/Event.scala

https://developer.mozilla.org/en-US/docs/Web/API/Event/composed

Add `Event.composed`

---

api-reports/2_12.txt
api-reports/2_13.txt
dom/src/main/scala/org/scalajs/dom/Element.scala

Hi! This just adds a facade. ~You might spot that when I ran `prePR` some of the API report formatting changed. I'm not sure why this is, but I'm happy to manually pluck those changes out if you like.~ (done)
[MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/Element/closest).

Add `Element#closest`

---

api-reports/2_12.txt
api-reports/2_13.txt
dom/src/main/scala-2/org/scalajs/dom/CanvasFillRule.scala
dom/src/main/scala-3/org/scalajs/dom/CanvasFillRule.scala
dom/src/main/scala/org/scalajs/dom/CanvasRenderingContext2D.scala
dom/src/main/scala/org/scalajs/dom/Path2D.scala

add Path2D and related methods

---

api-reports/2_12.txt
api-reports/2_13.txt
dom/src/main/scala/org/scalajs/dom/WebSocket.scala

Turns out that it's just an ordinary `Event`.
https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/error_event

Fix `WebSocket#onerror`

---

api-reports/2_12.txt
api-reports/2_13.txt
dom/src/main/scala/org/scalajs/dom/Element.scala
dom/src/main/scala/org/scalajs/dom/Node.scala

Resolves https://github.com/scala-js/scala-js-dom/issues/772

Remove attributes members from Node class

---

api-reports/2_12.txt
api-reports/2_13.txt
dom/src/main/scala/org/scalajs/dom/HTMLAnchorElement.scala

Add `HTMLAnchorElement#download`

---

api-reports/2_12.txt
api-reports/2_13.txt
dom/src/main/scala/org/scalajs/dom/intl/DateTimeFormatOptions.scala

add `DateTimeFormatOptions#fractionalSecondDigits`

---

api-reports/2_12.txt
api-reports/2_13.txt
dom/src/main/scala/org/scalajs/dom/URL.scala

See [here](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL_static#parameters).

Allow `MediaSource` to be passed in to `URL.createObjectURL`

---

api-reports/2_12.txt
api-reports/2_13.txt
dom/src/main/scala/org/scalajs/dom/Document.scala
dom/src/main/scala/org/scalajs/dom/ElementCreationOptions.scala

Also to `Document#createElementNS`
https://dom.spec.whatwg.org/#ref-for-dom-document-createelement
https://developer.mozilla.org/en-US/docs/Web/API/Document/createElement

Add `options` parameter to `Document#createElement`

---

api-reports/2_12.txt
api-reports/2_13.txt
dom/src/main/scala/org/scalajs/dom/FormData.scala

related issue https://github.com/scala-js/scala-js-dom/issues/798

Update dom/form data

---

api-reports/2_12.txt
api-reports/2_13.txt
dom/src/main/scala-2/org/scalajs/dom/CompressionFormat.scala
dom/src/main/scala-3/org/scalajs/dom/CompressionFormat.scala
dom/src/main/scala/org/scalajs/dom/CompressionStream.scala
dom/src/main/scala/org/scalajs/dom/DecompressionStream.scala

https://developer.mozilla.org/en-US/docs/Web/API/Compression_Streams_API

Add Compression APIs

---

api-reports/2_12.txt
api-reports/2_13.txt
dom/src/main/scala/org/scalajs/dom/XMLDocument.scala

`XMLDocument` is essentially just a marker class so this was extremely straightforward. Linking to https://github.com/scala-js/scala-js-dom/issues/771.

Add `XMLDocument`

---

api-reports/2_12.txt
api-reports/2_13.txt
dom/src/main/scala/org/scalajs/dom/DOMRectInit.scala
dom/src/main/scala/org/scalajs/dom/IntersectionObserver.scala
dom/src/main/scala/org/scalajs/dom/IntersectionObserverEntry.scala
dom/src/main/scala/org/scalajs/dom/IntersectionObserverEntryInit.scala
dom/src/main/scala/org/scalajs/dom/IntersectionObserverInit.scala

https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API

Add facade for Intersection Observer API

---

api-reports/2_12.txt
api-reports/2_13.txt
dom/src/main/scala/org/scalajs/dom/NavigatorContentUtils.scala

Add to Navigator the two protocol handler methods:
- registerProtocolHandler - https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler
- unregisterProtocolHandler - https://developer.mozilla.org/en-US/docs/Web/API/Navigator/unregisterProtocolHandler

Add Navigator's ProtocolHandler methods

---

project/build.properties

Somehow this broke our `prePR` command 🤔

Revert "Update sbt to 1.9.6"

---

api-reports/2_12.txt
api-reports/2_13.txt
dom/src/main/scala/org/scalajs/dom/ImageData.scala

Fixes https://github.com/scala-js/scala-js-dom/issues/807.
https://developer.mozilla.org/en-US/docs/Web/API/ImageData/data

Fix type of `ImageData#data`

---

api-reports/2_12.txt
api-reports/2_13.txt
dom/src/main/scala/org/scalajs/dom/NDEFMessage.scala
dom/src/main/scala/org/scalajs/dom/NDEFReader.scala
dom/src/main/scala/org/scalajs/dom/NDEFReadingEvent.scala
dom/src/main/scala/org/scalajs/dom/NDEFReadingEventInit.scala
dom/src/main/scala/org/scalajs/dom/NDEFRecord.scala
dom/src/main/scala/org/scalajs/dom/NDEFRecordInit.scala
dom/src/main/scala/org/scalajs/dom/NDEFScanOptions.scala
dom/src/main/scala/org/scalajs/dom/NDEFWriteOptions.scala

Web NFC API - https://developer.mozilla.org/en-US/docs/Web/API/Web_NFC_API

Add support for Web NFC API

---

api-reports/2_12.txt
api-reports/2_13.txt
dom/src/main/scala/org/scalajs/dom/Element.scala

Looks like these were missing from the `Element` facade:
* https://developer.mozilla.org/en-US/docs/Web/API/Element/hasPointerCapture
* https://developer.mozilla.org/en-US/docs/Web/API/Element/setPointerCapture
* https://developer.mozilla.org/en-US/docs/Web/API/Element/releasePointerCapture

Add `hasPointerCapture/releasePointerCapture/setPointerCapture` to `Element`

---

api-reports/2_12.txt
api-reports/2_13.txt
dom/src/main/scala/org/scalajs/dom/NDEFReadingEventInit.scala

I did a quick re-review of the WebNFC again and this should be it: https://github.com/scala-js/scala-js-dom/pull/806

fix: `NDEFReadingEventInit.serialNumber` returns a string

---

api-reports/2_12.txt
api-reports/2_13.txt
dom/src/main/scala/org/scalajs/dom/EventSource.scala

According to MDN the error of an EventSource is a generic Event instead of an ErrorEvent: https://developer.mozilla.org/en-US/docs/Web/API/EventSource/error_event
Just caught one of these underspecified errors in the wild :)

Generic error event for EventSource

---

api-reports/2_12.txt
api-reports/2_13.txt
dom/src/main/scala/org/scalajs/dom/CanvasRenderingContext2D.scala

Added the [`filter` property](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/filter) to the CanvasRenderingContext2D JavaScript class.

Added Canvas 2D filter property

---

api-reports/2_12.txt
dom/src/main/scala/org/scalajs/dom/Worker.scala

This PR adds two constructors for the Worker class which use the URL object rather than a String. This is relevant because some bundles like Parcel, even enforce you to use URL rather than a string.
More info about it here: https://developer.mozilla.org/en-US/docs/Web/API/Worker/Worker#url

URL constructor for Worker

---

api-reports/2_12.txt
api-reports/2_13.txt
dom/src/main/scala/org/scalajs/dom/MathMLElement.scala
tests-shared/src/main/scala/org/scalajs/dom/tests/shared/BrowserTests.scala

* run `sbt prePR` [x]
* commit changes to `api-reports` [x]
This proposes a base class for MathML elements. 
If it gets merged / agreed, I'd propose to follow it up with concrete elements following the style of the SVG elements, and the documentation here;
https://developer.mozilla.org/en-US/docs/Web/MathML
Related;
- https://github.com/raquo/scala-dom-types/pulls
- https://github.com/raquo/Laminar/issues/172
cc @raquo

Proposal for MathML base class

---

api-reports/2_12.txt
api-reports/2_13.txt
dom/src/main/scala/org/scalajs/dom/URL.scala

`URL.searchParams` is a readonly field. The URLSearchParams object itself is mutable, but the reference is immutable and stable.
https://url.spec.whatwg.org/#dom-url-searchparams
https://developer.mozilla.org/en-US/docs/Web/API/URL/searchParams
Note – in JS strict mode (typical for JS bundlers), `const url = new URL('http://localhost/').searchParams = new URLSearchParams({foo: "123"})` throws a `TypeError` saying that searchParams is a readonly field, but in the browser dev console, such an assignment will fail silently instead. You can check that the assignment failed by printing `url.searchParams.size == 0` or comparing the new and old references.
My testing and reading of the spec seems to confirm that it should be a `val`, not a `def`, at least I couldn't find anything contradicting …

Make dom.URL.searchParams readonly (val)
