src/main/scala/org/scalajs/dom/raw/lib.scala

Following on from convo in gitter.im chat

WindowTimers timeout types from Int to Double

---

src/main/scala/org/scalajs/dom/raw/lib.scala

Relevant Spec
http://www.w3.org/TR/DOM-Level-3-XPath/xpath.html#XPathResult

Added index parameter to XPathResult.snapshotItem

---

src/main/scala/org/scalajs/dom/ext/Extensions.scala

Added a method to AjaxException to check for timeout status.

---

src/main/scala/org/scalajs/dom/raw/lib.scala

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/serviceWorker

Add ServiceWorker

---

src/main/scala/org/scalajs/dom/raw/lib.scala

Add support for ClipboardEvent.

Add ClipboardEvent

---

src/main/scala/org/scalajs/dom/raw/lib.scala

Fix #118: Make MessageChannel a class.

---

src/main/scala/org/scalajs/dom/raw/Html.scala

Some miscellaneous fixes that have been hanging around for longer than necessary.

Fix #48: HTMLScriptElement.onload, mutable Document.body

---

src/main/scala/org/scalajs/dom/experimental/Vibration.scala

Get the ball rolling with  `org.scalajs.dom.experimental`. by adding the vibration api

Add experimental Vibration API

---

src/main/scala/org/scalajs/dom/experimental/Notification.scala

Supersedes #148 with a few additional fixes I did myself.

Add the Notification API.

---

src/main/scala/org/scalajs/dom/ext/Extensions.scala

Allow you to pass FormData (file upload).

Add a FormData to InputData implicit conversion.

---

src/main/scala/org/scalajs/dom/raw/lib.scala

- toggle with force parameter added
see also https://dom.spec.whatwg.org/#interface-domtokenlist

fix DomTokenList interface

---

readme/Index.scalatex

The readme lies.  Make it more honest.

Update readme to allow experimental packages.

---

src/main/scala/org/scalajs/dom/raw/lib.scala

window.location.origin should be UndefOr due to IE

---

src/main/scala/org/scalajs/dom/package.scala
src/main/scala/org/scalajs/dom/raw/lib.scala

Add support for the [Page Visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API)

add PageVisibility API

---

src/main/scala/org/scalajs/dom/experimental/webrtc/WebRTC.scala

Promise broken, here comes another PR :)

Fix #209. Add RTCDataChannelEvent. Add more ScalaDoc.

---

src/main/scala/org/scalajs/dom/experimental/beacon/package.scala

Add support for the [Beacon API](https://www.w3.org/TR/2016/WD-beacon-20160204/) (experimental)

add experimental Beacon API

---

src/main/scala/org/scalajs/dom/experimental/Fullscreen.scala
src/main/scala/org/scalajs/dom/experimental/PointerLock.scala

That's the last one for the moment :) (promised!).

Add experimental PointerLock and Fullscreen API

---

project/build.sbt
src/main/scala/org/scalajs/dom/crypto/Crypto.scala
src/main/scala/org/scalajs/dom/experimental/Fetch.scala
src/main/scala/org/scalajs/dom/experimental/Fullscreen.scala
src/main/scala/org/scalajs/dom/experimental/Stream.scala
src/main/scala/org/scalajs/dom/experimental/mediastream/MediaStream.scala
src/main/scala/org/scalajs/dom/experimental/push/PushManager.scala
src/main/scala/org/scalajs/dom/experimental/serviceworkers/ServiceWorkers.scala
src/main/scala/org/scalajs/dom/experimental/webrtc/WebRTC.scala
src/main/scala/org/scalajs/dom/raw/Audio.scala
src/main/scala/org/scalajs/dom/raw/Idb.scala
src/main/scala/org/scalajs/dom/raw/lib.scala
src/main/scala/org/scalajs/dom/raw/package.scala

Remove dom.raw.Promise. Remove invalid js.native annotations.

Upgrade to scalajs-0.6.7

---

src/main/scala/org/scalajs/dom/raw/WebWorkers.scala

The doc and second-argument were incorrect.
Reference: https://developer.mozilla.org/en-US/docs/Web/API/Worker/postMessage

Fix Worker signatures

---

project/build.properties

Update the sbt version to 0.13.11.

Set sbt version to 0.13.11

---

src/main/scala/org/scalajs/dom/raw/Audio.scala

Add the close(), suspend(), and resume() methods as well
as the state field to the AudioContext.

Add a few missing methods/fields to AudioContext

---

src/main/scala/org/scalajs/dom/raw/lib.scala

See https://drafts.csswg.org/cssom/#the-stylesheetlist-interface

StyleSheetList.item() doesn’t have a default value.

---

src/main/scala/org/scalajs/dom/raw/Css.scala
src/main/scala/org/scalajs/dom/raw/lib.scala

See:
* https://drafts.csswg.org/cssom/#the-stylesheet-interface
* https://drafts.csswg.org/cssom/#the-cssstylesheet-interface

Move href from CSSStyleSheet to StyleSheet.

---

build.sbt

Point source map links to Github

---

src/main/scala/org/scalajs/dom/experimental/mediastream/MediaStream.scala

New PR for the updated MediaStream, with proper branch and all!

Updated MediaStream to the 2016 specs

---

src/main/scala/org/scalajs/dom/raw/lib.scala

See https://developer.mozilla.org/de/docs/Web/API/StorageEvent

Fix oldValue and newValue types for StorageEvent

---

src/main/scala/org/scalajs/dom/experimental/permissions/package.scala

see https://developer.mozilla.org/en-US/docs/Web/API/PermissionStatus/onchange

Make PermissionStatus.onchange a var

---

src/main/scala/org/scalajs/dom/experimental/permissions/package.scala

Link to [specification](https://w3c.github.io/permissions/#push)

PermissionState.onchange and PushPermissionDescriptor

---

src/main/scala/org/scalajs/dom/raw/lib.scala

authoritative source: https://developer.mozilla.org/en-US/docs/Web/API/Node/innerText

Add innerText attribute to Node

---

src/main/scala/org/scalajs/dom/raw/lib.scala

Fix #280: Allow nodeValue to set value.

---

src/main/scala/org/scalajs/dom/raw/Html.scala

Remove invalid HTMLImageElement.create 

---

src/main/scala/org/scalajs/dom/experimental/intl/Intl.scala

Fix #384: Make locales optional in DateTimeFormat & NumberFormat.

---

.github/workflows/ci.yml
build.sbt
project/build.properties
project/build.sbt
src/main/scala/org/scalajs/dom/crypto/Crypto.scala
src/main/scala/org/scalajs/dom/experimental/intl/Intl.scala
src/main/scala/org/scalajs/dom/ext/package.scala

Rebases @russwyte's work in #446 per @sjrd's review comment.

Support Scala 3

---

src/main/scala/org/scalajs/dom/raw/lib.scala

https://developer.mozilla.org/en-US/docs/Web/API/Window/closed

Add window.closed property

---

.github/workflows/ci.yml
build.sbt
project/build.properties

Use sbt 1.5 on 1.x branch

---

api-reports/2_12.txt
api-reports/2_13.txt
src/main/scala/org/scalajs/dom/experimental/serviceworkers/ServiceWorkers.scala

https://developer.mozilla.org/en-US/docs/Web/API/FetchEvent#methods
Another one that came up in https://github.com/http4s/http4s/pull/5089.

FetchEvent extends ExtendableEvent

---

api-reports/2_12.txt
api-reports/2_13.txt
src/main/scala/org/scalajs/dom/raw/lib.scala

https://w3c.github.io/FileAPI/#dfn-load-event

Fix FileReader {abort,error,load} event types

---

build.sbt

Fix CI detection

---

build.sbt

...And Justice For @armanbilge

Fix developer ordering, latest maintainers on top

---

api-reports/2_12.txt
api-reports/2_13.txt
src/main/scala/org/scalajs/dom/Fetch.scala

https://fetch.spec.whatwg.org/#request-class

Fix #516 Request extends Body

---

api-reports/2_12.txt
api-reports/2_13.txt
src/main/scala/org/scalajs/dom/lib.scala

Fixes https://github.com/scala-js/scala-js-dom/issues/444

Add Node.baseURI

---

api-reports/2_12.txt
api-reports/2_13.txt
src/main/scala/org/scalajs/dom/lib.scala

Fixes https://github.com/scala-js/scala-js-dom/issues/443

add Node.isConnected

---

api-reports/2_12.txt
api-reports/2_13.txt
src/main/scala/org/scalajs/dom/lib.scala

Add remove and other missing Element methods

---

api-reports/2_12.txt
api-reports/2_13.txt
src/main/scala/org/scalajs/dom/lib.scala

querySelectorAll returns Elements, not Nodes

---

api-reports/2_12.txt

@japgolly I'm a little concerned why this needed a second pass, and furthermore why master is green without it.

prePR master

---

api-reports/2_12.txt
api-reports/2_13.txt
src/main/scala/org/scalajs/dom/experimental/beacon/package.scala
src/main/scala/org/scalajs/dom/experimental/gamepad/package.scala

Followup to https://github.com/scala-js/scala-js-dom/pull/572#discussion_r704857284.

Remove unnecessary implicit conversions

---

api-reports/2_12.txt
api-reports/2_13.txt
src/main/scala/org/scalajs/dom/experimental/PointerLock.scala
src/main/scala/org/scalajs/dom/lib.scala

Migrate PointerLock to dom

---

api-reports/2_12.txt
api-reports/2_13.txt
src/main/scala/org/scalajs/dom/DeviceOrientation.scala
src/main/scala/org/scalajs/dom/experimental/deviceorientation/package.scala

Towards #545.
@japgolly apologies, I very stupidly pushed this commit directly to master at first (reverted now) ... I thought branch protections would prevent this?

Migrate DeviceOrientation to dom

---

.scala-steward.conf

I'm following the directions provided in https://github.com/scala-js/scala-js-dom/pull/610#issue-760447297.

Ignore all scala updates

---

api-reports/2_12.txt
api-reports/2_13.txt
dom/src/main/scala/org/scalajs/dom/EventListenerOptions.scala

Somehow, there's always one more facade to add 😆 
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#parameters

Add `EventListenerOptions#signal`

---

api-reports/2_12.txt
api-reports/2_13.txt
dom/src/main/scala/org/scalajs/dom/html.scala

Add alias to HTMLDialogElement.

Add alias to HTMLDialogElement in html object.

---

dom/src/main/scala/org/scalajs/dom/Blob.scala

`Blob#slice` doc fix

---

dom/src/main/scala/org/scalajs/dom/HTMLAnchorElement.scala

Fix doc in HTMLAnchorElement.scala

---

dom/src/main/scala/org/scalajs/dom/URLSearchParams.scala

Fixes #834
I ran `sbt prePR` but didn't see any changes.

Fix URLSearchParams constructor parameters
